name: DOM
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy==2.1.3
  - rich==13.9.4
  - nbformat==5.10.4
  - ipykernel==6.29.3
  - pandas==2.2.3
  - plotly==5.24.1
  - ipywidgets==7.8.5
  - moviepy==1.0.3
  - pip